services:
- docker
sudo: required
script:
- sudo make test
- make deploy
before_install:
- openssl aes-256-cbc -K $encrypted_e8a559067d36_key -iv $encrypted_e8a559067d36_iv
  -in id_rsa.enc -out id_rsa -d
- chmod 700 id_rsa
- make install-yq
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
env:
  global:
    secure: A9L8lrfXQ6sapVrhG2gyihZ4+7VhXflzLRa++1QcbB0AU2sTkUFfIinipGuad9ishFXrjRLzQLYip/P1UPpZTC8bjJPSOPzxjgm5Y0VGpRPAp6GPFEOVEpVvi9bAWOrSTE4Xro9UcTrgUkIqu6KFnuug+aLs0KNuclRn0gunXsoc0DW+j2HsDQich4rc4VVN7QV4OilyMLuPhk3O3KPcgyZVbd3lYktoq+cpNs8LrrNXzqB8QxOclI/0aQ99QiCCglhSiZpUeO76dKcOUrMthaFq3lqxOPaYuiQnr/rvrtFQfNNWJ+wnm+1+JMuN6RsDGgoea73HXLXybDiIGudGoltMyXtrnHvps1BhGMtP+xqC2OhMuvbbguisJtK4wAx0A8wOasA2jLo3FmJzmmnA7w8AIDj3WXnRxSMFs/7Nz35qUzeibDEqAlDrRrg6ayI1nfjW+jEiLixYtzhCiPOMMoJ+20LwHIeIgH37kkcLiCL7zGKe2J3iFoKBBGenmPc97YTXtAD31UxWTnPO78bjzypy0v1Win5rvX6kIwuzrlwrmBdJpQP9io5UQzTMQdi60uG34a7i8HhW2fcqEkLcjqMNwtesdzgEPDD/2lX7MrmI+G0wYV1VzajvRYQ9Ykiyc4ZVSu8AxyXxfhT/Bid4tYnciHJHH2k+xWDO0BX2FAc=
notifications:
  slack:
    rooms:
      secure: HT+WAjcJcW8GRs7wZwlulIZOBB+QlsyOtKnrxjiDdCANKbEJFZXHrBmMiQJn8LzXd7/XsmQVVagyHG9A7ACYsipIs8HIzkGlI8ZiP/qxPQB1LJgDVR1GUwOhzwto26oi0Xb5yFrmwapOxGy73k6v8C4bPFO6QMDfh4YpGeHqbGv/k2FbkOd8Gnr3J1/lDiLU3VZ2EUvsCQi0M1Acu6rx5D6e9wwVN6NwWC/6ksx/3Sx2dzM/4BX5pi4QvKQY0NQn4POWgkEuo3t+r4zrnntUe5Ym23HpordL+j0MAQeg5RDgBt1PAbxmKbH+euHcbdGCyOTlOWcrK0Q3Ve64DI8GV1E4N1b30Sk56IJ/b3Wp1Zvbh5rKWLC9MO4uUzonSTTlIZ6fAu+HukOYB0ezHw2XGQBfnGefCbOUAJRxl7f9iJybWj2+Yx82CQ9yKm674Y/nTw0G73YM8Z0WPgbT5RVY4Gfr5hEFqA4kei4VUXGjiKO9jR5H8SvmTaTXeVX8DR5ymuwx0WY66M/Wu149hG+aBbGlZYEffTw6Jks/zl2FiSZcZA5IQHDL2earN0lrFp78A7ljH4By6ljoFTDfqQ5snz0hA9M8UTBdODq30o25tVjsl+S+XY9RrRrb4Gu1wDHsq1vgCI2Cd+4K+cgp1ZPYgh6ezyq+6icbyJrhPQfYDZ8=
