services:
- docker
sudo: required
script:
- sudo make test
- make deploy
before_install:
- openssl aes-256-cbc -K $encrypted_e8a559067d36_key -iv $encrypted_e8a559067d36_iv
  -in id_rsa.enc -out id_rsa -d
env:
  global:
    secure: A9L8lrfXQ6sapVrhG2gyihZ4+7VhXflzLRa++1QcbB0AU2sTkUFfIinipGuad9ishFXrjRLzQLYip/P1UPpZTC8bjJPSOPzxjgm5Y0VGpRPAp6GPFEOVEpVvi9bAWOrSTE4Xro9UcTrgUkIqu6KFnuug+aLs0KNuclRn0gunXsoc0DW+j2HsDQich4rc4VVN7QV4OilyMLuPhk3O3KPcgyZVbd3lYktoq+cpNs8LrrNXzqB8QxOclI/0aQ99QiCCglhSiZpUeO76dKcOUrMthaFq3lqxOPaYuiQnr/rvrtFQfNNWJ+wnm+1+JMuN6RsDGgoea73HXLXybDiIGudGoltMyXtrnHvps1BhGMtP+xqC2OhMuvbbguisJtK4wAx0A8wOasA2jLo3FmJzmmnA7w8AIDj3WXnRxSMFs/7Nz35qUzeibDEqAlDrRrg6ayI1nfjW+jEiLixYtzhCiPOMMoJ+20LwHIeIgH37kkcLiCL7zGKe2J3iFoKBBGenmPc97YTXtAD31UxWTnPO78bjzypy0v1Win5rvX6kIwuzrlwrmBdJpQP9io5UQzTMQdi60uG34a7i8HhW2fcqEkLcjqMNwtesdzgEPDD/2lX7MrmI+G0wYV1VzajvRYQ9Ykiyc4ZVSu8AxyXxfhT/Bid4tYnciHJHH2k+xWDO0BX2FAc=
