version: "3"
services:
    nginx:
        image: nginx:latest
        depends_on:
            - akuszyk
            - marmyandme
            - budjot
            - gitlab-issue-comments
        ports: 
            - "80:80"
            - "443:443"
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
            - ./certs/:/data/letsencrypt/
            - ./certs/etc/letsencrypt/:/etc/letsencrypt/
    akuszyk:
        image: andykuszyk/akuszyk:a9ac719
    marmyandme:
        image: andykuszyk/marmyandme:e30079f
    budjot:
        image: andykuszyk/budjot:ae2ad36
        depends_on:
          - mongo
        environment:
          - MONGOURL=mongodb://mongo:27017/budjot
    mongo:
        image: mongo:latest
        volumes:
          - $HOME/.mongo:/data/db 
    gitlab-issue-comments:
        image: andykuszyk/gitlab-issue-comments:latest
        environment:
            - GITLAB_TOKEN=abc123
