version: "3"
services:
    nginx:
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
            - /root/certs-data/:/data/letsencrypt/
            - /etc/letsencrypt/:/etc/letsencrypt/
    mongo:
        volumes:
            - /data/mongo:/data/db
    gitlab-issue-comments:
        environment:
            - GITLAB_TOKEN=gitlabtoken
