version: "3"
services:
    nginx:
        image: nginx:latest
        depends_on:
            - budjot
            - gitlab-issue-comments
        ports: 
            - "80:80"
            - "443:443"
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
            - ./certs/:/data/letsencrypt/
            - ./certs/etc/letsencrypt/:/etc/letsencrypt/
    cronical:
        image: andykuszyk/cronical:v1.0.0
    budjot:
        image: andykuszyk/budjot:ae2ad36
        depends_on:
          - mongo
        environment:
          - MONGOURL=mongodb://mongo:27017/budjot
    mongo:
        image: mongo:latest
        volumes:
          - $HOME/.mongo:/data/db 
    gitlab-issue-comments:
        image: andykuszyk/gitlab-issue-comments:latest
        environment:
            - GITLAB_TOKEN=abc123
    promtail:
      image: grafana/promtail:master
      volumes:
        - ./promtail.yaml:/etc/promtail/config.yaml
        - /var/log:/var/log
