on: push
jobs:
  deploy:
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
      OPENCART_USERNAME: ${{ secrets. OPENCART_USERNAME }}
      OPENCART_PASSWORD: ${{ secrets. OPENCART_PASSWORD }}
      OPENCART_EMAIL: ${{ secrets. OPENCART_EMAIL }}
      OPENCART_DATABASE_USER: ${{ secrets. OPENCART_DATABASE_USER }}
      OPENCART_DATABASE_PASSWORD: ${{ secrets. OPENCART_DATABASE_PASSWORD }}
      MARIADB_ROOT_PASSWORD: ${{ secrets. MARIADB_ROOT_PASSWORD }}
      DOUSER: ${{ secrets. DOUSER }}
      DOIP: ${{ secrets. DOIP }}
      ID_RSA: ${{ secrets. ID_RSA }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
      - run: sudo make test
      - run: echo "$ID_RSA" > id_rsa && chmod 700 id_rsa
      - run: echo "$KNOWN_HOSTS" > ~/.ssh/known_hosts
      - run: make install-yq
      - run: make deploy
